name: Build and Deploy (Dispatch)
on:
 push:
   branches:
     - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Build npm
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn
          yarn run build
  RepoAjobs:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: check if need to send the hook
        id: changes
        run: |
          if [[ $(git diff --name-only HEAD^ HEAD | grep  -E -i -w -v "^helm|^.github") ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "no changes to dispatch"
          fi

      - if: steps.changes.outputs.changes == 'true'
        name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DEVOPS_TOKEN  }}
          repository: ${{ secrets.dispatch_repo }}
          event-type: gitops-${{ github.event.repository.name }}-${{ github.ref }}-${{ github.actor }}
          client-payload: >-
            {
              "product": "platform",
              "project": "external",
              "type": "docker",
              "repository": "${{ github.event.repository.name }}" ,
              "repository_full": "${{ github.event.repository.full_name }}" ,
              "github-sha": "${{ github.sha }}",
              "github-actor": "${{ github.actor }}",
              "github-ref": "${{ github.ref_name }}",
            }
